sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Wenuo's Blog
name: Wenuo
description: Simple Life
copyright_time: 2019
url: https://Wenuo.github.io
github: https://github.com/Wenuo
email: mailto:yeaoyu991219@gmail.com
rss: false

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
